#############################################################################
# Makefile for building: ArtBoomerang-Qt
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  abm-qt.pro
# Template: app
# Command: E:\deps\Qt-5.4.1\bin\qmake.exe -o Makefile abm-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:\deps\Qt-5.4.1\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: abm-qt.pro ../../deps/Qt-5.4.1/mkspecs/win32-g++/qmake.conf ../../deps/Qt-5.4.1/mkspecs/features/spec_pre.prf \
		../../deps/Qt-5.4.1/mkspecs/qdevice.pri \
		../../deps/Qt-5.4.1/mkspecs/features/device_config.prf \
		../../deps/Qt-5.4.1/mkspecs/common/shell-win32.conf \
		../../deps/Qt-5.4.1/mkspecs/qconfig.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_clucene_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_core.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_core_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_gui.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_gui_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_help.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_help_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_network.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_network_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_sql.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_sql_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_testlib.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_testlib_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_uitools.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_uitools_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_widgets.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_widgets_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_xml.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_lib_xml_private.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_qico.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_qminimal.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_qwindows.pri \
		../../deps/Qt-5.4.1/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../deps/Qt-5.4.1/mkspecs/features/qt_functions.prf \
		../../deps/Qt-5.4.1/mkspecs/features/qt_config.prf \
		../../deps/Qt-5.4.1/mkspecs/features/win32/qt_config.prf \
		../../deps/Qt-5.4.1/mkspecs/win32-g++/qmake.conf \
		../../deps/Qt-5.4.1/mkspecs/features/spec_post.prf \
		../../deps/Qt-5.4.1/mkspecs/features/exclusive_builds.prf \
		../../deps/Qt-5.4.1/mkspecs/features/default_pre.prf \
		../../deps/Qt-5.4.1/mkspecs/features/win32/default_pre.prf \
		../../deps/Qt-5.4.1/mkspecs/features/resolve_config.prf \
		../../deps/Qt-5.4.1/mkspecs/features/exclusive_builds_post.prf \
		../../deps/Qt-5.4.1/mkspecs/features/default_post.prf \
		../../deps/Qt-5.4.1/mkspecs/features/win32/rtti.prf \
		../../deps/Qt-5.4.1/mkspecs/features/precompile_header.prf \
		../../deps/Qt-5.4.1/mkspecs/features/warn_on.prf \
		../../deps/Qt-5.4.1/mkspecs/features/qt.prf \
		../../deps/Qt-5.4.1/mkspecs/features/resources.prf \
		../../deps/Qt-5.4.1/mkspecs/features/moc.prf \
		../../deps/Qt-5.4.1/mkspecs/features/uic.prf \
		../../deps/Qt-5.4.1/mkspecs/features/win32/windows.prf \
		../../deps/Qt-5.4.1/mkspecs/features/testcase_targets.prf \
		../../deps/Qt-5.4.1/mkspecs/features/exceptions.prf \
		../../deps/Qt-5.4.1/mkspecs/features/yacc.prf \
		../../deps/Qt-5.4.1/mkspecs/features/lex.prf \
		abm-qt.pro \
		E:/deps/Qt-5.4.1/lib/qtmain.prl \
		E:/deps/Qt-5.4.1/lib/Qt5Core.prl \
		E:/deps/Qt-5.4.1/lib/Qt5Widgets.prl \
		E:/deps/Qt-5.4.1/lib/Qt5Gui.prl \
		E:/deps/Qt-5.4.1/lib/Qt5Network.prl \
		E:/deps/Qt-5.4.1/plugins/platforms/qwindows.prl \
		E:/deps/Qt-5.4.1/lib/Qt5PlatformSupport.prl \
		E:/deps/Qt-5.4.1/plugins/imageformats/qico.prl \
		E:/deps/Qt-5.4.1/plugins/bearer/qgenericbearer.prl \
		E:/deps/Qt-5.4.1/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) -o Makefile abm-qt.pro
..\..\deps\Qt-5.4.1\mkspecs\features\spec_pre.prf:
..\..\deps\Qt-5.4.1\mkspecs\qdevice.pri:
..\..\deps\Qt-5.4.1\mkspecs\features\device_config.prf:
..\..\deps\Qt-5.4.1\mkspecs\common\shell-win32.conf:
..\..\deps\Qt-5.4.1\mkspecs\qconfig.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_concurrent.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_core.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_core_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_gui.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_gui_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_help.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_help_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_network.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_network_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_printsupport.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_sql.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_sql_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_testlib.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_uitools.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_widgets.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_xml.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_lib_xml_private.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_qico.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\deps\Qt-5.4.1\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\deps\Qt-5.4.1\mkspecs\features\qt_functions.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\qt_config.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\win32\qt_config.prf:
..\..\deps\Qt-5.4.1\mkspecs\win32-g++\qmake.conf:
..\..\deps\Qt-5.4.1\mkspecs\features\spec_post.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\exclusive_builds.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\default_pre.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\win32\default_pre.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\resolve_config.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\exclusive_builds_post.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\default_post.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\win32\rtti.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\precompile_header.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\warn_on.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\qt.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\resources.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\moc.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\uic.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\win32\windows.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\testcase_targets.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\exceptions.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\yacc.prf:
..\..\deps\Qt-5.4.1\mkspecs\features\lex.prf:
abm-qt.pro:
E:/deps/Qt-5.4.1/lib/qtmain.prl:
E:/deps/Qt-5.4.1/lib/Qt5Core.prl:
E:/deps/Qt-5.4.1/lib/Qt5Widgets.prl:
E:/deps/Qt-5.4.1/lib/Qt5Gui.prl:
E:/deps/Qt-5.4.1/lib/Qt5Network.prl:
E:/deps/Qt-5.4.1/plugins/platforms/qwindows.prl:
E:/deps/Qt-5.4.1/lib/Qt5PlatformSupport.prl:
E:/deps/Qt-5.4.1/plugins/imageformats/qico.prl:
E:/deps/Qt-5.4.1/plugins/bearer/qgenericbearer.prl:
E:/deps/Qt-5.4.1/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile abm-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) E:\build\artboomerang\artboomerang-qt_plugin_import.cpp

E:/build/artboomerang/src/leveldb/libleveldb.a: FORCE

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
